---

- name: "Ensure {{ openvpn_configuration_directory }} exists"
  ansible.builtin.file:
    path: "{{ openvpn_configuration_directory }}"
    state: directory
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0750"

- name: client | Place client.conf
  ansible.builtin.template:
    src: client.conf.j2
    dest: "{{ openvpn_configuration_directory }}/client.conf"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - Restart openvpn
