---
# tasks file for openvpn

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install openvpn packages
  ansible.builtin.package:
    name: "{{ openvpn_packages }}"
    state: present

- name: Setup openvpn server or client
  ansible.builtin.include_tasks:
    file: "{{ openvpn_role }}.yml"

- name: Ensure openvpn directory exists
  ansible.builtin.file:
    path: "{{ openvpn_configuration_directory }}"
    state: directory
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0750"

- name: Update rc.conf to find the openvpn config file
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*openvpn_configfile\s*=(.*)$'
    line: 'openvpn_configfile="{{ openvpn_configuration_directory }}/{{ openvpn_role }}.conf"'
  when: ansible_os_family == "FreeBSD"
  notify: restart openvpn

- name: Start and enable openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: true
